<?php

namespace MediaRemoteBundle\Repository;

use MediaRemoteBundle\Entity\Media;
use MediaRemoteBundle\Entity\Remote;

/**
 * MediaRemoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRemoteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     * @return array
     */
    public function findByRemoteName(string $name) : array
    {
        $remote = $this
        ->getEntityManager()
        ->getRepository(Remote::class)
        ->findOneByRemoteName($name);
        return $this->findByRemote($remote);
    }
    
    /**
     * 
     * @param string $remoteName
     * @param string $mediaName
     * @return MediaRemote|NULL
     */
    public function findByRemoteNameAndMediaName(string $remoteName, string $mediaName)
    {
        return $this
        ->findOneBy([
            "remote" => $this
            ->getEntityManager()
            ->getRepository(Remote::class)
            ->findOneByRemoteName($remoteName),
            "media"  => $this
            ->getEntityManager()
            ->getRepository(Media::class)
            ->findOneByMediaName($mediaName)
        ]);
    }
    
}
