<?php

namespace MediaRemoteBundle\Repository;

use MediaRemoteBundle\Entity\Remote;

/**
 * RemoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDefaultRemoteName()
    {
        return $this
        ->getEntityManager()
        ->getRepository(Remote::class)
        ->findOneBy([])
        ->getRemoteName();
    }
}
