# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                owner:
                  password: $2y$12$uq5S3sajd7tvTYgwq67x5.hPyyihY4RAbhZJt2uxH580H0FqHPmKq
                  roles: ROLE_SUPER_ADMIN
                maintener:
                  password: $2y$12$xkqeDJDJ3IEZzeHO3SU/yuWrFEiMMp063308oorTypbD2Ct57TOsi
                  roles: ROLE_ADMIN
                  
    encoders:
        Symfony\Component\Security\Core\User\User:
          algorithm: bcrypt
          cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]        
            
    access_control:
        - { path: ^/remote, roles: ROLE_ADMIN }            
